///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test_Project_1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Test_Project_1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    [RepositoryFolder("2ff1cc81-f727-4ef2-a4ee-f52fdf906ecc")]
    public partial class Test_Project_1Repository : RepoGenBaseFolder
    {
        static Test_Project_1Repository instance = new Test_Project_1Repository();

        /// <summary>
        /// Gets the singleton class instance representing the Test_Project_1Repository element repository.
        /// </summary>
        [RepositoryFolder("2ff1cc81-f727-4ef2-a4ee-f52fdf906ecc")]
        public static Test_Project_1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Test_Project_1Repository() 
            : base("Test_Project_1Repository", "/", null, 0, false, "2ff1cc81-f727-4ef2-a4ee-f52fdf906ecc", ".\\RepositoryImages\\Test_Project_1Repository2ff1cc81.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2ff1cc81-f727-4ef2-a4ee-f52fdf906ecc")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    public partial class Test_Project_1RepositoryFolders
    {
    }
#pragma warning restore 0436
}